### ISSUE TITLE
textinput can't display in native model but in terminal

### ISSUE THREAD

**Issue by Devil-Ryu** [zauberzeug/nicegui#1205]
### Description

when i use native model to start the program, i found that, the input element don't work, and my input display in the terminal.
the problem occurs on macos, normal on windows，following is my versions：
```
macos                Ventural 13.4.1
nicegui                   1.3.4
pywebview                 4.2.2
```

the code as follows:
```python
from nicegui import app, ui

app.native.window_args['resizable'] = False
app.native.start_args['debug'] = True

ui.input("input")
ui.textarea("")
ui.label('app running in native mode')
ui.button('enlarge', on_click=lambda: app.native.main_window.resize(1000, 700))

ui.run(native=True, window_size=(400, 300), fullscreen=False)
```
following is the problem
![image](https://github.com/zauberzeug/nicegui/assets/46808006/81c99563-a39c-40b4-95e9-29d010e5ef19)

**Comment by falkoschindler** [comment]
Hi @Devil-Ryu,

Could this be a dark mode issue? It looks like your system has dark mode activated. Maybe the input text is white and therefore invisible. Can you try disabling dark mode? This would help to narrow it down. Thanks!

**Comment by Devil-Ryu** [comment]
I turned the input background-color into blue and the problem still exists
![image](https://github.com/zauberzeug/nicegui/assets/46808006/c4095ffb-c8cf-4ec9-acaa-aa4ce681f22f)
you can see in the picture the cursor in the input element do not move
@falkoschindler

**Comment by falkoschindler** [comment]
Unfortunately I can't reproduce the problem. I tried Python3.9, 3.10 and 3.11. And I upgraded pywebview from 4.0.2 to 4.2.2.

Maybe it has something to do with you local setup. Are there any non-standard accessibility or language settings on your system?

Has anyone else experienced something similar?

**Comment by Devil-Ryu** [comment]
i packaged the program, and the input dispaly correctly, but wen i run in the terminal , the problem still exists.

**Comment by rodja** [comment]
Super strange. Maybe it's something in your environment. Could you try as a different user, on an other machine or different shell? Maybe try with pip and virtual environment?

**Comment by Devil-Ryu** [comment]
My friend used my code on his mac, and the same problem occurred, he use miniconda to create a virtual environment, I used anaconda.

**Comment by falkoschindler** [comment]
Can you, please, double-check that you're running exactly the code you posted? The screenshot doesn't fit, because there's no textarea visible.

**Comment by Devil-Ryu** [comment]
I ran it again and found that the output was not redirected to the terminal, but rather that the focus did not locate in the input box after I clicked on it (there may be other claims, which I currently refer to as the focus). For example, if I first click on the code area and then click on the input box to input, the input content will still be in the code area. If I click on the browser's search box and then click on the input box, So the input is still in the browser search box

**Comment by falkoschindler** [comment]
I can't follow. But as far as I understand: You didn't focus the input element, but typed in the terminal window. That's why I was asking about which code you're running: Since there is no print statement in your example, we shouldn't see any output in the terminal.

To me it looks like the original issue is resolved. Can you confirm that?

**Comment by Devil-Ryu** [comment]
just like this
![Untitled](https://github.com/zauberzeug/nicegui/assets/46808006/c226c989-07c5-4424-911d-6616edf60938)

**Comment by Devil-Ryu** [comment]
Perhabs it's the pywebview's problem, i tried and still cannot input
![Kapture 2023-07-24 at 17 21 07](https://github.com/zauberzeug/nicegui/assets/46808006/5cd5d92c-6f25-40b7-b690-75f22d200e68)

**Comment by falkoschindler** [comment]
@Devil-Ryu Yes, that's what I though. Thanks for investigating!
I'll close this issue, because there doesn't seem to be anything we can do. But feel free to share your insights if you find the root cause.

**Comment by wllbll** [comment]
I countered this issue either, and found a solution in this thread, https://github.com/r0x0r/pywebview/issues/66 , that's 
run main.py below instead
`pythonw main.py`
I seems this issue related to conda
